from pathlib import Path
import json
import pandas as pd


def write_management_summary(path, mart, risk, quality_pareto, model_metrics, forecast_metrics, data_trust):
    latest=mart.iloc[-1]; latest_risk=risk.iloc[-1]
    text=f"""# MEDNEXUS Management Analytical Summary\n\n**Disclosure:** MEDNEXUS is a fictional enterprise. All enterprise operating data in this default build is synthetic. Scenario outputs are simulated and predictive outputs are model-derived.\n\n## Latest synthetic operating period\n\n- Revenue: ${latest['revenue']:,.0f}\n- Operating cost: ${latest['operating_cost']:,.0f}\n- OEE: {latest['oee']:.1%}\n- OLI: {latest['oli']:.1%}\n- FPY: {latest['fpy']:.1%}\n- On-time delivery: {latest['on_time_delivery']:.1%}\n- Capacity gap: {latest['capacity_gap_pct']:.1%}\n- MORI: {latest_risk['mori_score']:.1f} ({latest_risk['mori_band']})\n- Data Trust Score: {data_trust:.1f}/100\n\n## Evidence layers\n\n- Quality concentration: top defect category is **{quality_pareto.iloc[0]['defect_category']}** ({quality_pareto.iloc[0]['share']:.1%} of defect units).\n- Predictive maintenance: selected model = **{model_metrics.get('model')}**; holdout PR-AUC = {model_metrics.get('pr_auc') if model_metrics.get('pr_auc') is not None else 'n/a'}; ROC-AUC = {model_metrics.get('roc_auc') if model_metrics.get('roc_auc') is not None else 'n/a'}; recall = {model_metrics.get('recall'):.3f}; Brier score = {model_metrics.get('brier_score'):.4f}. Selection used validation data only. These are model-derived values on synthetic data, not causal conclusions.\n- Demand forecasting: moving-average baseline RMSE = {forecast_metrics.get('rmse'):.2f}.\n\n## Decision principle\n\nUse the decision queue to prioritize investigation and controlled interventions. The evidence supports management attention and scenario testing; it does not establish causal effects for every observed relationship.\n"""
    Path(path).parent.mkdir(parents=True,exist_ok=True)
    Path(path).write_text(text,encoding='utf-8')
